#remote_theme: jcm236/jcm236.github.io@master

remote_theme: chrisrhymes/bulma-clean-theme@v1.0.4
# Site Settings
lang: en
title: PluginSmiths
tagline: Creating to help Create

description: >
  A group of devs making plugins for MCreator
baseurl: "/"
url: "https://pluginsmiths.github.io"
permalink: pretty
#favicon: /path/to/favicon.png
force_theme: 'light'
#hide_share_buttons: true
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
livereload: true
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from



#google_analytics: UA-code-here

markdown: kramdown
highlighter: rouge
collections_dir: 
collections:
  plugins: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

