remote_theme: chrisrhymes/bulma-clean-theme@v1.0.0


# Site Settings
lang: en
title: PluginSmiths
tagline: Creating to help Create

description: >
  A group of devs making plugins for MCreator
baseurl: "/"
url: "https://pluginsmiths.github.io"
permalink: pretty
#favicon: /path/to/favicon.png

#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from



#google_analytics: UA-code-here

markdown: kramdown
highlighter: rouge

collections:
  software: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
